url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Stochastic Systems Lab" # the name of your site, e.g. ACME Corp.
description: "Edwardson School, Purdue University"
